LANG, MAIN_MENU, MAIN_MENU_HANDLER, ABOUT_YANGEL, ABOUT_YANGEL_HANDLER, STARTUP, TECH_OR_MM, \
TECH_YES_NO, PROTOTYPE_YES_NO, EDU_YES_NO, TEAM_YES_NO, FANTASTIC_YES_NO, TRY_AGAIN_OR_MM, Q_ROUND_YES_NO, \
STARTUPER_NAME, STARTUPER_EMAIL, STARTUPER_IDEA, STARTUPER_PROTO, STARTUPER_WHY, STARTUPER_FINAL_Q,\
MENTOR_HANDLER, MENTOR_NAME, MENTOR_EXPERTISE, MENTOR_EXPERIENCE, MENTOR_SITE, MENTOR_EMAIL, MENTOR_FINAL_Q,\
PARTNER, PARTNER_HANDLER, PARTNER_NAME, PARTNER_ORG_NAME, PARTNER_ORG_POS, PARTNER_EMAIL, \
PARTNER_FINAL_Q, ADMIN_HANDLER, PUSH_TEXT, PUSH_WHO = range(37)
